### ISSUE TITLE
Thanks for your great  work

### ISSUE THREAD

**Issue by raozhongyu** [Stanford-ILIAD/CARLO#2]
Thanks for your great  work, I'm quite interested in your work, I'd like to konw would you  release your whole code with the carlo env or carla env

**Comment by ebiyik** [comment]
Hello,

Thank you for your interest and kind words! This repo (master branch) contains only the simulation environment we have developed and used in the [H-ReIL paper](https://arxiv.org/abs/2007.00178). The full training pipeline is not available online, as it makes use of multiple other works, but it should be easy to replicate it. Simply, you can (i) wrap the scenario in [example_intersection.py](https://github.com/Stanford-ILIAD/CARLO/blob/master/example_intersection.py) as an [OpenAI Gym](https://gym.openai.com/) environment, (ii) collect some data on it (using either the policy we provided, some human-collected data or any other control policy), (iii) train behavioral cloning or [CoIL](https://github.com/felipecode/coiltraine) policies using those data, and finally (iv) train the high-level RL policy using [OpenAI baselines](https://github.com/openai/baselines) or [stable-baselines](https://github.com/hill-a/stable-baselines).
