### ISSUE TITLE
Sample code

### ISSUE THREAD

**Issue by PhanindraParashar** [Stanford-ILIAD/CARLO#3]
How can we start using this simulator for training ?

**Comment by ebiyik** [comment]
Hello,

This repo (master branch) contains only the simulation environment we have developed and used in the [H-ReIL paper](https://arxiv.org/abs/2007.00178). The full training pipeline is not available online, as it makes use of multiple other works, but it should be easy to replicate it. Simply, you can (i) wrap the scenario in [example_intersection.py](https://github.com/Stanford-ILIAD/CARLO/blob/master/example_intersection.py) as an [OpenAI Gym](https://gym.openai.com/) environment, (ii) collect some data on it (using either the policy we provided, some human-collected data or any other control policy), (iii) train behavioral cloning or [CoIL](https://github.com/felipecode/coiltraine) policies using those data, and finally (iv) train the high-level RL policy using [OpenAI baselines](https://github.com/openai/baselines) or [stable-baselines](https://github.com/hill-a/stable-baselines).

The step (i) above also makes it possible to run any OpenAI-Gym-environment-compatible RL algorithm (e.g. [OpenAI baselines](https://github.com/openai/baselines) and [stable-baselines](https://github.com/hill-a/stable-baselines)) to work on CARLO. For an example of this, you can see this repository that we created for a class homework: [https://github.com/PrinciplesofRobotAutonomy/CS237B_HW3](https://github.com/PrinciplesofRobotAutonomy/CS237B_HW3). Inside the [gym_carlo/envs directory](https://github.com/PrinciplesofRobotAutonomy/CS237B_HW3/tree/master/gym_carlo/envs), you can find a few different CARLO scenarios wrapped as OpenAI Gym environments.

Hope this helps!
