### ISSUE TITLE
OpenAI Gym Wrapper

### ISSUE THREAD

**Issue by tedpyne** [Stanford-ILIAD/CARLO#4]
Hello,

Thank you for your great work. I am hoping to use CARLO for my masters thesis. Would it be possible for you to share one of the environments wrapped in a OpenAI Gym wrapper as an example?

Thanks once again!

**Comment by ebiyik** [comment]
Hello,

Sure! Can you check this repository that makes use of CARLO: https://github.com/PrinciplesofRobotAutonomy/CS237B_HW3 ? In that repository, [gym_carlo/envs/intersection_scenario.py](https://github.com/PrinciplesofRobotAutonomy/CS237B_HW3/blob/master/gym_carlo/envs/intersection_scenario.py) and [gym_carlo/envs/lanechange_scenario.py](https://github.com/PrinciplesofRobotAutonomy/CS237B_HW3/blob/master/gym_carlo/envs/lanechange_scenario.py) are examples of CARLO scenarios wrapped as OpenAI Gym environments. They might be using an older version of CARLO, but the wrapping process should be very similar, if not the same.

**Comment by tedpyne** [comment]
Fantastic! Thank you for these resources Erdem. I will make sure to share how I make use of CARLO during my thesis with you.
